import prisma from "@/models/libs/prisma";

export async function POST(request) {
  const {
    id,
    id_user,
    nik_ayah,
    nama_ayah,
    tempat_lahir_ayah,
    tanggal_lahir_ayah,
    pendidikan_ayah,
    pekerjaan_ayah,
    penghasilan_ayah,
    no_hp_ayah,
    nik_ibu,
    nama_ibu,
    tempat_lahir_ibu,
    tanggal_lahir_ibu,
    pendidikan_ibu,
    pekerjaan_ibu,
    penghasilan_ibu,
    no_hp_ibu,
    nik_wali,
    nama_wali,
    tempat_lahir_wali,
    tanggal_lahir_wali,
    pendidikan_wali,
    pekerjaan_wali,
    penghasilan_wali,
    no_hp_wali,
  } = await request.json();

  const data = {
    id,
    id_user,
    nik_ayah,
    nama_ayah,
    tempat_lahir_ayah,
    tanggal_lahir_ayah,
    pendidikan_ayah,
    pekerjaan_ayah,
    penghasilan_ayah,
    no_hp_ayah,
    nik_ibu,
    nama_ibu,
    tempat_lahir_ibu,
    tanggal_lahir_ibu,
    pendidikan_ibu,
    pekerjaan_ibu,
    penghasilan_ibu,
    no_hp_ibu,
    nik_wali,
    nama_wali,
    tempat_lahir_wali,
    tanggal_lahir_wali,
    pendidikan_wali,
    pekerjaan_wali,
    penghasilan_wali,
    no_hp_wali,
  };

  const updateData = await prisma.data_orangtua.update({
    where: { id_user: data.id_user },
    data: {
      id,
    id_user,
    nik_ayah,
    nama_ayah,
    tempat_lahir_ayah,
    tanggal_lahir_ayah,
    pendidikan_ayah,
    pekerjaan_ayah,
    penghasilan_ayah,
    no_hp_ayah,
    nik_ibu,
    nama_ibu,
    tempat_lahir_ibu,
    tanggal_lahir_ibu,
    pendidikan_ibu,
    pekerjaan_ibu,
    penghasilan_ibu,
    no_hp_ibu,
    nik_wali,
    nama_wali,
    tempat_lahir_wali,
    tanggal_lahir_wali,
    pendidikan_wali,
    pekerjaan_wali,
    penghasilan_wali,
    no_hp_wali,
    status: "Pending"
    },
  });

  if (!updateData) return Response.json({ status: 500, isUpdate: false });
  else return Response.json({ status: 200, isUpdate: true });
}
